language: node_js

node_js:
  - lts/*

notifications:
  email: false

jobs:
  include:
    - stage: release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
