language: node_js

node_js:
  - lts/*

notifications:
  email: false

cache:
  npm: true

jobs:
  include:
    - stage: test
      script:
        - npm run test

    - stage: release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
